export type SuggestedChecklist = {
  id: string
  name: string
  category: string
  description: string
  recommendedPriority: "Baixa" | "Média" | "Alta" | "Urgente"
  items: string[]
}

export const suggestedChecklists: SuggestedChecklist[] = [
  {
    id: "landing-page",
    name: "Landing Page",
    category: "Criação web",
    description: "Estrutura completa para criar uma página de conversão com briefing, copy, layout, publicação e revisão.",
    recommendedPriority: "Alta",
    items: [
      "Confirmar objetivo da página",
      "Definir público e oferta principal",
      "Coletar referências e materiais do cliente",
      "Criar estrutura das seções",
      "Escrever chamada principal e textos de apoio",
      "Criar layout desktop e mobile",
      "Configurar formulário ou botão de contato",
      "Testar responsividade",
      "Revisar links, textos e imagens",
      "Publicar e validar com o cliente",
    ],
  },
  {
    id: "site-institucional",
    name: "Site Institucional",
    category: "Criação web",
    description: "Checklist para entregar um site profissional com páginas, conteúdo, responsividade e publicação.",
    recommendedPriority: "Alta",
    items: [
      "Mapear páginas necessárias",
      "Coletar logo, cores, imagens e textos",
      "Definir navegação principal",
      "Criar layout da página inicial",
      "Criar páginas internas",
      "Configurar SEO básico",
      "Testar formulário de contato",
      "Testar responsividade",
      "Revisar conteúdo com o cliente",
      "Publicar domínio e hospedagem",
    ],
  },
  {
    id: "identidade-visual",
    name: "Identidade Visual",
    category: "Design",
    description: "Organiza uma entrega de identidade visual do briefing até os arquivos finais.",
    recommendedPriority: "Alta",
    items: [
      "Aplicar briefing de marca",
      "Mapear referências visuais",
      "Definir direção criativa",
      "Criar primeiras propostas",
      "Apresentar opções ao cliente",
      "Refinar proposta escolhida",
      "Definir paleta e tipografia",
      "Preparar variações da marca",
      "Exportar arquivos finais",
      "Enviar guia básico de uso",
    ],
  },
  {
    id: "social-media",
    name: "Social Media",
    category: "Marketing",
    description: "Fluxo para planejar, produzir e revisar conteúdos de redes sociais.",
    recommendedPriority: "Média",
    items: [
      "Definir objetivo da campanha",
      "Levantar temas e referências",
      "Criar calendário de posts",
      "Escrever legendas",
      "Criar artes ou vídeos",
      "Revisar identidade visual",
      "Enviar para aprovação",
      "Agendar publicações",
      "Conferir posts publicados",
      "Registrar aprendizados",
    ],
  },
  {
    id: "trafego-pago",
    name: "Tráfego Pago",
    category: "Marketing",
    description: "Checklist para preparar, lançar e acompanhar campanhas pagas.",
    recommendedPriority: "Urgente",
    items: [
      "Definir objetivo da campanha",
      "Validar público e orçamento",
      "Conferir página de destino",
      "Configurar pixel ou tag de conversão",
      "Criar anúncios e variações",
      "Configurar campanha na plataforma",
      "Revisar segmentação",
      "Publicar campanha",
      "Monitorar primeiras métricas",
      "Registrar ajustes necessários",
    ],
  },
  {
    id: "manutencao-site",
    name: "Manutenção de Site",
    category: "Suporte",
    description: "Organiza ajustes, testes e validação de manutenção sem esquecer etapas críticas.",
    recommendedPriority: "Média",
    items: [
      "Entender solicitação do cliente",
      "Validar acesso ao ambiente",
      "Fazer backup quando necessário",
      "Aplicar ajuste solicitado",
      "Testar páginas impactadas",
      "Testar mobile",
      "Verificar formulário e links",
      "Registrar o que foi alterado",
      "Enviar atualização ao cliente",
    ],
  },
  {
    id: "atendimento-cliente",
    name: "Atendimento ao Cliente",
    category: "Relacionamento",
    description: "Checklist para organizar solicitações, retornos e próximos passos com clientes.",
    recommendedPriority: "Média",
    items: [
      "Registrar solicitação recebida",
      "Confirmar entendimento do pedido",
      "Definir próximo passo",
      "Estimar prazo de retorno",
      "Executar ou encaminhar demanda",
      "Responder cliente com status",
      "Registrar decisão ou pendência",
      "Agendar follow-up se necessário",
    ],
  },
  {
    id: "reuniao-briefing",
    name: "Reunião/Briefing",
    category: "Planejamento",
    description: "Ajuda a preparar, conduzir e registrar uma reunião importante com cliente.",
    recommendedPriority: "Média",
    items: [
      "Definir objetivo da reunião",
      "Listar perguntas principais",
      "Separar referências ou materiais",
      "Confirmar horário e participantes",
      "Registrar decisões tomadas",
      "Registrar pendências",
      "Definir responsáveis",
      "Enviar resumo para o cliente",
      "Criar próximas tarefas",
    ],
  },
  {
    id: "entrega-revisao",
    name: "Entrega/Revisão",
    category: "Qualidade",
    description: "Checklist final para revisar uma entrega antes de enviar ao cliente.",
    recommendedPriority: "Alta",
    items: [
      "Conferir escopo combinado",
      "Revisar conteúdo e ortografia",
      "Testar links e botões",
      "Testar visual no mobile",
      "Validar arquivos finais",
      "Preparar mensagem de entrega",
      "Enviar para aprovação",
      "Registrar feedback recebido",
      "Aplicar ajustes finais",
    ],
  },
]

export function getSuggestedChecklist(id: string) {
  return suggestedChecklists.find((checklist) => checklist.id === id) ?? null
}
